os: linux
dist: xenial
language: shell

env:
  global:
    - DOCKER_IMAGE: baloise/gitopscli
    # DOCKER_USERNAME
    - secure: "Ecq9r+yXVc9gVdn1e4sDS/yegMKOyN3F6f4jxNSNl1pEkBZayVOvl6seh58sK+QzaIOLlrMYNlOzmWIKaekRuskYLJNYMUh67RJB24knOMSbA0hD3WPO8GbFY1Y/Xe1Gk5zKlLqFKe9OoCbM0ItGIXL2DrFPWl94F1YoZim2h7q6lFEo9NHvYSjreGMcqJujQKoN5/UkO76C3TEKNFXbyxev18nHwXQvqC2axbZONYEQuzYC7dDDAHRMxQ25t2qcWh19f/ssl0qR7VYheBY72Pypvl131+qIxaMl+r/7UeKHnhrM2/ineyo8VPfxhHwar31ldu0YyC0KtSYEMERASsKmJNyaP9d3mo6Vciws/8fGaU0FqlwfRPOhaa/ixMS43qJ4NS9vSogteQJVIIC4B9mHmFvzShDK5aDML+KJ0ehQnayS/30AywS80iSkSWdbkKPAdr+djVhUbey+LAWPVdmJOnIiBET4eSFqJ37dXmcKrhUcfrthL2SftkTGZ4Fm4gHPNYWXIej9N6kTwHlYzRkuJN3PNTLsqp9YE6dUYIUZEu0qkyX2IBljdOxLK5UTKzdkD+j8kLFEP2kN1ELbhP4qEBJj17swycTP9wR4RB+FfjsdeTXonaEOGq8z2CctnczJe87TJ1/GuRj5l/VXiK2ph25El/Axhg5Kv3lHxJw="
    # DOCKER_PASSWORD
    - secure: "gnQCC722E9vE6HEL6LwSS6tHdbKkhNX0gPwbVMYZWkfQiVBic9543j6Tdu6BWZbtPzTvdfQmOLoojK/srTpBpr3zdUTCwDlm8hoO6PtiYbaUMwaI/9mUI2s+Td3MKCzKLkQWOWY6+aiMooVXFZXRiHOrQaiXnKtnQnZcrEMe0il8z/71j1Tm1FofZXdPf94ycjCRW/gi1aRTkl3m5VufOsV9D3fo4/OSF4cjS8UXYyjAPWIbk5cyro/UtTAwjXnOroXFrQ2AQGlrII09ipPc/AczJd2KTRRHcAb2yME4PE9hGI67U2kRIVPuZKdt/pHhyibjgJV1UZocQ53sExhF0pnu8vUOIbM9pUf+qYJF/7aRtrLHPek3+JGYcmclJK2ZSPqAHtbh51H3Hkiq/OFw7zK+I36RcILH7imcapbVb391sLF6Q0bTRo2yeQA3GODQ5B3HUEBaDgMjDzqObEpyGyGk16UL2k5+zvZTS4mBxs5wJ+tl/cAYHBdyRG6wC7g2gAnsat3yJbdpUeaWz1PNUXRh0oIQnYXk9zfG7EeIEvFdvQL9kA7d1fLS4ojshvwv0Wsg7oqin/d8kyE+8qBXkVLdC/iGIdgXiNPcZc9VY9cCSJiEUy/s0F3xeGIDOVnuxuBMEb33O+r6HBSZejkAqUVnJvOebSy279jZJ36nuTw="
    # GITHUB_TOKEN
    - secure: "gOx7jOLQXH3ujdTF70Z1ucEV7LLXmealDPzHX+n6gUtTJE7OkQfdfzxncxjOSBdRXuhzpoaZrPrNiWeuoR8M3o2bqirlWrwn8osaHjXKu7T1SLnQxhFgH5zn2oZlYXqoryOF0GL5W1IKulGaCnOqBUvZkSmY2vAdx8PMzlMH7+f09+JPn6TyyBLBAROTPfb/NU95p/ZMXwFEPMbiRQp7IrGwdQlAFNqUVEh158GAmx3E5THX5EDPuUsk3Kl1MOqzkSFuBSmUOZdl6WrWpr+W6oB8TaQbjZJH1qQiPhi0GTsSt4v7BGRK93z8y8AVQrQqgfLMjvSWXBoXOJE7B9K/6RDFCQBGaN7Yaw2zvEEsIaN1PoH8xmozu6iaSePT0lL91weWPxMJzP5dnKELtd7snxtE07j1E1kx/MXSIlcYgaV1IOpWgidZAMe3SUfClZAGc1HlJd3IjMXB0RF5dq0tdgFfCWITIi+G6Qnzr1RLmop5iKvGeguYy/2y8BiWxorzeEVWuTmNERHbCaoj9i3uxwdmR8bRBTosyAsVpeJ6XUSJVxRQVa2r7u3xSOrWBJ9g4LFMy1HZGEf+TYodMz6t2Kz5mYeY6lXMYXAaLg/MT/xEBRLhX4ypHf5XegMDviHATQ76LYqOsXOr1O98SgYiVHvTl7955pq1m5zCZeudWrE="

jobs:
  include:
    - stage: test
      language: shell
      services: docker
      script: docker build .
    - stage: doc
      language: python
      python: 3.6
      install: pip install -r requirements-dev.txt
      script: mkdocs build
      deploy:
        provider: pages
        strategy: git
        local_dir: site
        token: $GITHUB_TOKEN
        keep_history: true
        skip_cleanup: true
        on:
          branch: master
    - stage: release
      language: node_js
      node_js: lts/*
      services: docker
      install:
        - npm install semantic-release
                      @semantic-release/exec
                      @google/semantic-release-replace-plugin
                      conventional-changelog-conventionalcommits
      script: npx semantic-release

stages:
  - name: test
  - name: doc
  - name: release
    if: branch = master AND type = push

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
