services:
  - docker

env:
  global:
    # DOCKER_USERNAME
    - secure: "mW+7G47eUTjiJrl9DdP8fScdis5cHqp5gfwgvRmhrjOx3xKP606Yi3tBPc/N6s+iJHwvllLl/jkzUo5vOnBYxC+1w1DKQX+AsaYtASM+wFinusyct69v5vZIqw9z5FoSQxK43fQkJqmGiJpm0IWm7NapDTiuXmJHp7kaeGPVZdvbsDNGF1ke9EPEdLdu61jNme3XAiLas7Dtk0w//3rcXbqIDDOgosu/TC7uEYzgL3kVygONFGOcdXxK50M0871YFln9ol/XSgyIja7F7lTqzih2E/4BQKvgSZ3HAYFc6ejDGXqZ38suOU8X23rsgIfWURB+4FsR3IEFOIKcoSH9oHk/alo7arvvomaFHDtYSy+a+w2uEUiqVgOCiI6DXa90Rb1ADVi3CUGAsyUccLyrcNhDbLJjGVMt5NiHZZCm5dmWEUSr+L7F77LbkH345IzCUtZXy1gVwENSMxNFAzpkuZwwTYTD0tv7lZ8prC2nX/4VSKDA6DvsLiQXe9pqbEr8rtOwdQ0QA/NRQYlXhfE+mQEmAiWJnxUvlbXyO6BCr8WsuvJAFG53fZ0VU7rBoNvmLZNFcuzQDFnj0KYpQ3AmB8n9VyY4x5G1ZWGsdmwlMJVddpT1qgSzweu21O0bI70Oj7Ii8e2JjOwvamXm8JjtLh4Ya1iWIRTt3zvhylPegEA="
    # DOCKER_ACCESS_TOKEN
    - secure: "cyp11ZUB/GJ3o96oFZvMEZPW0rPzWnOHXcQTgQcQBz328+OUBgg/rY61BwRAjk57Kqjr9w7FWCJCjvzHLiTk/wVwsKo3pQw9nJPiyblFKAtGunJfA/rrwVqaDTvki9zWtQKqwteQ9gPpVG4RAsCVVYp0nCsCCfmBsw6iWnHSiQKwpw2g23PTG97xkioFcMNdetdt1+fqQC23fcEd7aktPlq0wRilSOZQRk87zF9tiRzTIL9Cl81guh0xC5FY4KG6egS82DAv0gANQO/aJr2vWpTZRPukL5GkFUpFfRFcH9nszz39R8OQ5B+SWJxbWSkbIN0k5IQyZyN7rWqQkk1p84JSMn3O4/0RSrAXDp93dcb1OxAYQq0o+upBZfcpKBFAAXy0xIHKu8uQe2BohREB2EVlfQIO1iXYnB2hUo7hUyHFQ2btjT1Qq8GdU1uudKmaueDC51WlHmcvBgAptQXD4ESagiL5vSCfw4S7gUevdrxrV+GLkUYGxqzd20CA0kWf05KBYX3JHh02sTwQm+x8cQWL4aHQ/vQN+zYRLh+TrgoOKoR50L5xK1Eyq3boTZ0R6wOcvKgA9ViWZ2ZDckB2FlM2Vpk4Zvmg5cBlgTwP96aQXh06TZgfvx26Ni9JaWb59iZSVSl1RWdeeIv5VZqLBX2MR5jy2rlccg8ws5DqWAQ="
    - IMAGE_NAME=baloiseincubator/gitopscli

script:
  - docker build -t $IMAGE_NAME:latest .
  - if [ -n "$TRAVIS_TAG" ]; then docker tag $IMAGE_NAME:$TRAVIS_TAG; fi
  - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
  - docker push $IMAGE_NAME:latest
  - if [ -n "$TRAVIS_TAG" ]; then docker push $IMAGE_NAME:$TRAVIS_TAG; fi
